
language: node_js

node_js:
    - "stable"
    - "14"
    - "12"
    - "10"
    - "8"
    - "6"
    - "4"

script:
    - >
      nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

      if [ $nodeVersionMajor -eq 14 ]; then
        npm run lint;
        npm test;
        npm run coverage;
        coveralls < coverage/lcov.info;
      else
        npm run test;
      fi;
