
language: node_js

node_js:
    - "stable"
    - "14"
    - "12"
    - "10"
    - "8"
    - "6"
    - "4"

script:
    - >
      nodeVersionMajor=`node --version | grep -Eo 'v[0-9]+' | sed 's/v//'`;

      if [ $nodeVersionMajor -eq 14 ]; then
        npm run lint
      fi;

    - >
      nodeVersionMajor=`node --version | grep -Eo 'v[0-9]+' | sed 's/v//'`;

      if [ $nodeVersionMajor -gt 4 ]; then
        npm test;
      else
        npm run testWithoutBail;
      fi;

    - >
      nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

      if [ $nodeVersionMajor -eq 14 ]; then
        echo "TODO: coverage needs to be fixed...";
      else
        echo "*** Do not make coverage reports for non node.js 14 builds ($nodeVersionMajor)";
      fi;

